{% set name = "qdrant-client" %}
{% set version = "1.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qdrant_client-{{ version }}.tar.gz
  sha256: 631f1f3caebfad0fd0c1fba98f41be81d9962b7bf3ca653bed3b727c0e0cbe0e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
    - setuptools
  run:
    - python >={{ python_min }}
    - httpx >=0.20.0
    - numpy >=1.21
    - pydantic >=1.10.8
    - grpcio >=1.41.0
    - grpcio-tools >=1.41.0
    - urllib3 >=1.26.14,<3
    - portalocker >=2.7.0,<3.0.0
  run_constrained:
    - fastembed >=0.2.5


test:
  imports:
    - qdrant_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qdrant/qdrant-client
  summary: Python client for Qdrant vector search engine
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
