{% set name = "qdrant-client" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qdrant_client-{{ version }}.tar.gz
  sha256: 65078d5328bc0393f42a46a31cd319a989b8285bf3958360acf1dffffdf4cc4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - httpx >=0.20.0
    - numpy >=1.21
    - pydantic >=1.10.8
    - grpcio >=1.41.0
    - grpcio-tools >=1.41.0
    - urllib3 >=1.26.14,<3
    - portalocker >=2.7.0,<3.0.0
  run_constrained:
    - fastembed >=0.2.5


test:
  imports:
    - qdrant_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qdrant/qdrant-client
  summary: Python client for Qdrant vector search engine
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
